# Generated by Django 3.0.8 on 2020-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201008_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingagent',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
