# Generated by Django 3.0.8 on 2020-10-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201008_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingagent',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
