# Generated by Django 3.0.8 on 2020-10-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pollingagent_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingagent',
            name='username',
        ),
    ]
