# Generated by Django 3.0.8 on 2020-10-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_pollingagent_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingagent',
            name='email',
        ),
    ]
