# Generated by Django 3.0.8 on 2020-10-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_pollingagent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingagent',
            name='phone_number',
        ),
    ]
