# Generated by Django 3.0.8 on 2020-10-13 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NON-COMPLIANCE', 'NON-COMPLIANCE'), ('LOGSITICS', 'LOGSITICS'), ('HARRSASEMENT', 'HARRSASEMENT'), ('INTERFERENCE', 'INTERFERENCE'), ('VIOLENCE', 'VIOLENCE'), ('DELAYS', 'DELAYS'), ('CONFUSION', 'CONFUSION'), ('CHAOS', 'CHAOS'), ('POWER FAILURE', 'POWER FAILURE')], max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='lat')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='lng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
