# Generated by Django 3.0.8 on 2020-10-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0002_auto_20201013_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
