# Generated by Django 3.0.8 on 2020-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0003_admin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password',
            new_name='password1',
        ),
    ]
