# Generated by Django 3.0.8 on 2020-10-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0005_auto_20201013_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
