# Generated by Django 3.0.8 on 2020-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0006_remove_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
