# Generated by Django 3.0.8 on 2020-10-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0008_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
