# Generated by Django 3.0.8 on 2020-10-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0009_remove_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
