# Generated by Django 3.0.8 on 2020-10-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0010_admin_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='avatar',
        ),
    ]
