# Generated by Django 3.0.8 on 2020-10-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election_watch', '0012_auto_20201015_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election_watch.Admin'),
        ),
    ]
